// Code generated by gen/schemagen from go-amino type information. DO NOT EDIT.
// Regenerate with: pnpm schemas

/* eslint-disable @stylistic/object-curly-newline, @stylistic/object-property-newline, max-lines, @typescript-eslint/no-explicit-any */

import type {
  Codec,
} from "../codec";
import {
  type StructType,
  t,
} from "../types";
import * as reprs from "./reprs";

const bitarray_BitArray = t.struct("bitarray.BitArray", {
  bits: t.int,
  elems: t.slice(t.uint64),
});

const merkle_ProofOp = t.struct("merkle.ProofOp", {
  type: t.string,
  key: t.bytes,
  data: t.bytes,
});

const merkle_Proof = t.struct("merkle.Proof", {
  ops: t.slice(merkle_ProofOp),
});

const merkle_SimpleProof = t.struct("merkle.SimpleProof", {
  total: t.int,
  index: t.int,
  leafHash: t.field(t.bytes, { json: "leaf_hash" }),
  aunts: t.slice(t.bytes),
});

const merkle_SimpleProofNode: StructType<any> = t.struct("merkle.SimpleProofNode", {
  hash: t.field(t.bytes, { json: "Hash" }),
  parent: t.field(t.pointer(t.lazy(() => merkle_SimpleProofNode)), { json: "Parent" }),
  left: t.field(t.pointer(t.lazy(() => merkle_SimpleProofNode)), { json: "Left" }),
  right: t.field(t.pointer(t.lazy(() => merkle_SimpleProofNode)), { json: "Right" }),
});

const secp256k1_PubKeySecp256k1 = t.byteArray(33);

const ed25519_PubKeyEd25519 = t.byteArray(32);

const crypto_PubKey = t.interface("crypto.PubKey");

const multisig_PubKeyMultisigThreshold = t.struct("multisig.PubKeyMultisigThreshold", {
  k: t.field(t.uint, { json: "threshold" }),
  pubKeys: t.field(t.slice(crypto_PubKey), { json: "pubkeys" }),
});

const abci_RequestBase = t.struct("abci.RequestBase", {});

const abci_RequestEcho = t.struct("abci.RequestEcho", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  message: t.field(t.string, { json: "Message" }),
});

const abci_RequestFlush = t.struct("abci.RequestFlush", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
});

const abci_RequestInfo = t.struct("abci.RequestInfo", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
});

const abci_RequestSetOption = t.struct("abci.RequestSetOption", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  key: t.field(t.string, { json: "Key" }),
  value: t.field(t.string, { json: "Value" }),
});

const abci_BlockParams = t.struct("abci.BlockParams", {
  maxTxBytes: t.field(t.int64, { json: "MaxTxBytes" }),
  maxDataBytes: t.field(t.int64, { json: "MaxDataBytes" }),
  maxBlockBytes: t.field(t.int64, { json: "MaxBlockBytes" }),
  maxGas: t.field(t.int64, { json: "MaxGas" }),
  timeIotaMS: t.field(t.int64, { json: "TimeIotaMS" }),
});

const abci_ValidatorParams = t.struct("abci.ValidatorParams", {
  pubKeyTypeURLs: t.field(t.slice(t.string), { json: "PubKeyTypeURLs" }),
});

const abci_ConsensusParams = t.struct("abci.ConsensusParams", {
  block: t.field(t.pointer(abci_BlockParams), { json: "Block" }),
  validator: t.field(t.pointer(abci_ValidatorParams), { json: "Validator" }),
});

const abci_ValidatorUpdate = t.struct("abci.ValidatorUpdate", {
  address: t.field(reprs.Address, { json: "Address" }),
  pubKey: t.field(crypto_PubKey, { json: "PubKey" }),
  power: t.field(t.int64, { json: "Power" }),
});

const abci_RequestInitChain = t.struct("abci.RequestInitChain", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  time: t.field(t.time, { json: "Time" }),
  chainID: t.field(t.string, { json: "ChainID" }),
  consensusParams: t.field(t.pointer(abci_ConsensusParams), { json: "ConsensusParams" }),
  validators: t.field(t.slice(abci_ValidatorUpdate), { json: "Validators" }),
  appState: t.field(t.interface(), { json: "AppState" }),
  initialHeight: t.field(t.int64, { json: "InitialHeight" }),
});

const abci_RequestQuery = t.struct("abci.RequestQuery", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  data: t.field(t.bytes, { json: "Data" }),
  path: t.field(t.string, { json: "Path" }),
  height: t.field(t.int64, { json: "Height" }),
  prove: t.field(t.bool, { json: "Prove" }),
});

const abci_Header = t.interface("abci.Header");

const abci_VoteInfo = t.struct("abci.VoteInfo", {
  address: t.field(reprs.Address, { json: "Address" }),
  power: t.field(t.int64, { json: "Power" }),
  signedLastBlock: t.field(t.bool, { json: "SignedLastBlock" }),
});

const abci_LastCommitInfo = t.struct("abci.LastCommitInfo", {
  round: t.field(t.int32, { json: "Round" }),
  votes: t.field(t.slice(abci_VoteInfo), { json: "Votes" }),
});

const abci_RequestBeginBlock = t.struct("abci.RequestBeginBlock", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  hash: t.field(t.bytes, { json: "Hash" }),
  header: t.field(abci_Header, { json: "Header" }),
  lastCommitInfo: t.field(t.pointer(abci_LastCommitInfo), { json: "LastCommitInfo" }),
});

const abci_RequestCheckTx = t.struct("abci.RequestCheckTx", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  tx: t.field(t.bytes, { json: "Tx" }),
  type: t.field(t.int, { json: "Type" }),
});

const abci_RequestDeliverTx = t.struct("abci.RequestDeliverTx", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  tx: t.field(t.bytes, { json: "Tx" }),
});

const abci_RequestEndBlock = t.struct("abci.RequestEndBlock", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
  height: t.field(t.int64, { json: "Height" }),
});

const abci_RequestCommit = t.struct("abci.RequestCommit", {
  requestBase: t.field(abci_RequestBase, { json: "RequestBase" }),
});

const abci_Error = t.interface("abci.Error");

const abci_Event = t.interface("abci.Event");

const abci_ResponseBase = t.struct("abci.ResponseBase", {
  error: t.field(abci_Error, { json: "Error" }),
  data: t.field(t.bytes, { json: "Data" }),
  events: t.field(t.slice(abci_Event), { json: "Events" }),
  log: t.field(t.string, { json: "Log" }),
  info: t.field(t.string, { json: "Info" }),
});

const abci_ResponseException = t.struct("abci.ResponseException", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
});

const abci_ResponseEcho = t.struct("abci.ResponseEcho", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  message: t.field(t.string, { json: "Message" }),
});

const abci_ResponseFlush = t.struct("abci.ResponseFlush", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
});

const abci_ResponseInfo = t.struct("abci.ResponseInfo", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  abciVersion: t.field(t.string, { json: "ABCIVersion" }),
  appVersion: t.field(t.string, { json: "AppVersion" }),
  lastBlockHeight: t.field(t.int64, { json: "LastBlockHeight" }),
  lastBlockAppHash: t.field(t.bytes, { json: "LastBlockAppHash" }),
});

const abci_ResponseSetOption = t.struct("abci.ResponseSetOption", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
});

const abci_ResponseDeliverTx = t.struct("abci.ResponseDeliverTx", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  gasWanted: t.field(t.int64, { json: "GasWanted" }),
  gasUsed: t.field(t.int64, { json: "GasUsed" }),
});

const abci_ResponseInitChain = t.struct("abci.ResponseInitChain", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  consensusParams: t.field(t.pointer(abci_ConsensusParams), { json: "ConsensusParams" }),
  validators: t.field(t.slice(abci_ValidatorUpdate), { json: "Validators" }),
  txResponses: t.field(t.slice(abci_ResponseDeliverTx), { json: "TxResponses" }),
});

const abci_ResponseQuery = t.struct("abci.ResponseQuery", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  key: t.field(t.bytes, { json: "Key" }),
  value: t.field(t.bytes, { json: "Value" }),
  proof: t.field(t.pointer(merkle_Proof), { json: "Proof" }),
  height: t.field(t.int64, { json: "Height" }),
});

const abci_ResponseBeginBlock = t.struct("abci.ResponseBeginBlock", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
});

const abci_ResponseCheckTx = t.struct("abci.ResponseCheckTx", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  gasWanted: t.field(t.int64, { json: "GasWanted" }),
  gasUsed: t.field(t.int64, { json: "GasUsed" }),
});

const abci_ResponseEndBlock = t.struct("abci.ResponseEndBlock", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  validatorUpdates: t.field(t.slice(abci_ValidatorUpdate), { json: "ValidatorUpdates" }),
  consensusParams: t.field(t.pointer(abci_ConsensusParams), { json: "ConsensusParams" }),
  events: t.field(t.slice(abci_Event), { json: "Events" }),
});

const abci_ResponseCommit = t.struct("abci.ResponseCommit", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
});

const abci_StringError = t.string;

const abci_EventString = t.string;

const bft_PartSetHeader = t.struct("bft.PartSetHeader", {
  total: t.int,
  hash: t.bytes,
});

const bft_BlockID = t.struct("bft.BlockID", {
  hash: t.bytes,
  partsHeader: t.field(bft_PartSetHeader, { json: "parts" }),
});

const bft_Proposal = t.struct("bft.Proposal", {
  type: t.field(t.uint8, { json: "Type" }),
  height: t.int64,
  round: t.int,
  polRound: t.field(t.int, { json: "pol_round" }),
  blockID: t.field(bft_BlockID, { json: "block_id" }),
  timestamp: t.time,
  signature: t.bytes,
});

const bft_Header = t.struct("bft.Header", {
  version: t.string,
  chainID: t.field(t.string, { json: "chain_id" }),
  height: t.int64,
  time: t.time,
  numTxs: t.field(t.int64, { json: "num_txs" }),
  totalTxs: t.field(t.int64, { json: "total_txs" }),
  appVersion: t.field(t.string, { json: "app_version" }),
  lastBlockID: t.field(bft_BlockID, { json: "last_block_id" }),
  lastCommitHash: t.field(t.bytes, { json: "last_commit_hash" }),
  dataHash: t.field(t.bytes, { json: "data_hash" }),
  validatorsHash: t.field(t.bytes, { json: "validators_hash" }),
  nextValidatorsHash: t.field(t.bytes, { json: "next_validators_hash" }),
  consensusHash: t.field(t.bytes, { json: "consensus_hash" }),
  appHash: t.field(t.bytes, { json: "app_hash" }),
  lastResultsHash: t.field(t.bytes, { json: "last_results_hash" }),
  proposerAddress: t.field(reprs.Address, { json: "proposer_address" }),
});

const bft_Data = t.struct("bft.Data", {
  txs: t.slice(t.bytes),
});

const bft_CommitSig = t.struct("bft.CommitSig", {
  type: t.uint8,
  height: t.int64,
  round: t.int,
  blockID: t.field(bft_BlockID, { json: "block_id" }),
  timestamp: t.time,
  validatorAddress: t.field(reprs.Address, { json: "validator_address" }),
  validatorIndex: t.field(t.int, { json: "validator_index" }),
  signature: t.bytes,
});

const bft_Commit = t.struct("bft.Commit", {
  blockID: t.field(bft_BlockID, { json: "block_id" }),
  precommits: t.field(t.slice(t.pointer(bft_CommitSig)), { nilElements: true }),
});

const bft_Block = t.struct("bft.Block", {
  header: bft_Header,
  data: bft_Data,
  lastCommit: t.field(t.pointer(bft_Commit), { json: "last_commit" }),
});

const bft_Vote = t.struct("bft.Vote", {
  type: t.uint8,
  height: t.int64,
  round: t.int,
  blockID: t.field(bft_BlockID, { json: "block_id" }),
  timestamp: t.time,
  validatorAddress: t.field(reprs.Address, { json: "validator_address" }),
  validatorIndex: t.field(t.int, { json: "validator_index" }),
  signature: t.bytes,
});

const bft_Part = t.struct("bft.Part", {
  index: t.int,
  bytes: t.bytes,
  proof: merkle_SimpleProof,
});

const bft_CanonicalPartSetHeader = t.struct("bft.CanonicalPartSetHeader", {
  total: t.field(t.uint32, { json: "Total" }),
  hash: t.field(t.bytes, { json: "Hash" }),
});

const bft_CanonicalBlockID = t.struct("bft.CanonicalBlockID", {
  hash: t.field(t.bytes, { json: "Hash" }),
  partsHeader: t.field(bft_CanonicalPartSetHeader, { json: "PartsHeader" }),
});

const bft_CanonicalProposal = t.struct("bft.CanonicalProposal", {
  type: t.field(t.uint8, { json: "Type" }),
  height: t.field(t.int64, { json: "Height", fixed64: true }),
  round: t.field(t.int64, { json: "Round", fixed64: true }),
  polRound: t.field(t.int64, { json: "POLRound", varint: true }),
  blockID: t.field(bft_CanonicalBlockID, { json: "BlockID" }),
  timestamp: t.field(t.time, { json: "Timestamp" }),
  chainID: t.field(t.string, { json: "ChainID" }),
});

const bft_CanonicalVote = t.struct("bft.CanonicalVote", {
  type: t.field(t.uint8, { json: "Type" }),
  height: t.field(t.int64, { json: "Height", fixed64: true }),
  round: t.field(t.int64, { json: "Round", fixed64: true }),
  blockID: t.field(bft_CanonicalBlockID, { json: "BlockID" }),
  timestamp: t.field(t.time, { json: "Timestamp" }),
  chainID: t.field(t.string, { json: "ChainID" }),
});

const bft_Validator = t.struct("bft.Validator", {
  address: reprs.Address,
  pubKey: t.field(crypto_PubKey, { json: "pub_key" }),
  votingPower: t.field(t.int64, { json: "voting_power" }),
  proposerPriority: t.field(t.int64, { json: "proposer_priority" }),
});

const bft_ValidatorSet = t.struct("bft.ValidatorSet", {
  validators: t.slice(t.pointer(bft_Validator)),
  proposer: t.pointer(bft_Validator),
});

const bft_EventNewBlock = t.struct("bft.EventNewBlock", {
  block: t.pointer(bft_Block),
  resultBeginBlock: t.field(abci_ResponseBeginBlock, { json: "result_begin_block" }),
  resultEndBlock: t.field(abci_ResponseEndBlock, { json: "result_end_block" }),
});

const bft_EventNewBlockHeader = t.struct("bft.EventNewBlockHeader", {
  header: bft_Header,
  resultBeginBlock: t.field(abci_ResponseBeginBlock, { json: "result_begin_block" }),
  resultEndBlock: t.field(abci_ResponseEndBlock, { json: "result_end_block" }),
});

const bft_TxResult = t.struct("bft.TxResult", {
  height: t.int64,
  index: t.uint32,
  tx: t.bytes,
  response: abci_ResponseDeliverTx,
});

const bft_EventTx = t.struct("bft.EventTx", {
  result: bft_TxResult,
});

const bft_EventVote = t.struct("bft.EventVote", {
  vote: t.pointer(bft_Vote),
});

const bft_EventString = t.string;

const bft_EventValidatorSetUpdates = t.struct("bft.EventValidatorSetUpdates", {
  validatorUpdates: t.field(t.slice(abci_ValidatorUpdate), { json: "validator_updates" }),
});

const bft_DuplicateVoteEvidence = t.struct("bft.DuplicateVoteEvidence", {
  pubKey: t.field(crypto_PubKey, { json: "PubKey" }),
  voteA: t.field(t.pointer(bft_Vote), { json: "VoteA" }),
  voteB: t.field(t.pointer(bft_Vote), { json: "VoteB" }),
});

const std_VestingSchedule = t.struct("std.VestingSchedule", {
  originalVesting: t.field(reprs.Coins, { json: "original_vesting", omitEmpty: true }),
  startTime: t.field(t.int64, { json: "start_time", omitEmpty: true }),
  endTime: t.field(t.int64, { json: "end_time", omitEmpty: true }),
  type: t.field(t.string, { omitEmpty: true }),
});

const std_BaseAccount = t.struct("std.BaseAccount", {
  address: reprs.Address,
  coins: reprs.Coins,
  pubKey: t.field(crypto_PubKey, { json: "public_key" }),
  accountNumber: t.field(t.uint64, { json: "account_number" }),
  sequence: t.uint64,
  vesting: t.field(std_VestingSchedule, { omitEmpty: true }),
});

const std_BaseSessionAccount = t.struct("std.BaseSessionAccount", {
  baseAccount: t.field(std_BaseAccount, { json: "BaseAccount" }),
  masterAddress: t.field(reprs.Address, { json: "master_address" }),
  expiresAt: t.field(t.int64, { json: "expires_at" }),
  spendLimit: t.field(reprs.Coins, { json: "spend_limit", omitEmpty: true }),
  spendPeriod: t.field(t.int64, { json: "spend_period", omitEmpty: true }),
  spendUsed: t.field(reprs.Coins, { json: "spend_used", omitEmpty: true }),
  spendReset: t.field(t.int64, { json: "spend_reset", omitEmpty: true }),
});

const std_Coin = reprs.Coin;

const std_GasPrice = t.struct("std.GasPrice", {
  gas: t.int64,
  price: std_Coin,
});

const std_Msg = t.interface("std.Msg");

const std_Fee = t.struct("std.Fee", {
  gasWanted: t.field(t.int64, { json: "gas_wanted" }),
  gasFee: t.field(std_Coin, { json: "gas_fee" }),
});

const std_Signature = t.struct("std.Signature", {
  pubKey: t.field(crypto_PubKey, { json: "pub_key" }),
  signature: t.bytes,
  sessionAddr: t.field(reprs.Address, { json: "session_addr", omitEmpty: true }),
});

const std_Tx = t.struct("std.Tx", {
  msgs: t.field(t.slice(std_Msg), { json: "msg" }),
  fee: std_Fee,
  signatures: t.slice(std_Signature),
  memo: t.string,
});

const std_MemFile = t.struct("std.MemFile", {
  name: t.string,
  body: t.string,
});

const std_MemPackage = t.struct("std.MemPackage", {
  name: t.string,
  path: t.string,
  files: t.slice(t.pointer(std_MemFile)),
  type: t.field(t.interface(), { omitEmpty: true }),
  info: t.field(t.interface(), { omitEmpty: true }),
});

const std_InternalError = t.struct("std.InternalError", {});

const std_TxDecodeError = t.struct("std.TxDecodeError", {});

const std_InvalidSequenceError = t.struct("std.InvalidSequenceError", {});

const std_UnauthorizedError = t.struct("std.UnauthorizedError", {});

const std_InsufficientFundsError = t.struct("std.InsufficientFundsError", {});

const std_UnknownRequestError = t.struct("std.UnknownRequestError", {});

const std_InvalidAddressError = t.struct("std.InvalidAddressError", {});

const std_UnknownAddressError = t.struct("std.UnknownAddressError", {});

const std_InvalidPubKeyError = t.struct("std.InvalidPubKeyError", {});

const std_InsufficientCoinsError = t.struct("std.InsufficientCoinsError", {});

const std_InvalidCoinsError = t.struct("std.InvalidCoinsError", {});

const std_InvalidGasWantedError = t.struct("std.InvalidGasWantedError", {});

const std_OutOfGasError = t.struct("std.OutOfGasError", {});

const std_MemoTooLargeError = t.struct("std.MemoTooLargeError", {});

const std_InsufficientFeeError = t.struct("std.InsufficientFeeError", {});

const std_TooManySignaturesError = t.struct("std.TooManySignaturesError", {});

const std_NoSignaturesError = t.struct("std.NoSignaturesError", {});

const std_GasOverflowError = t.struct("std.GasOverflowError", {});

const std_RestrictedTransferError = t.struct("std.RestrictedTransferError", {});

const std_SessionExpiredError = t.struct("std.SessionExpiredError", {});

const std_SessionNotFoundError = t.struct("std.SessionNotFoundError", {});

const std_SessionLimitError = t.struct("std.SessionLimitError", {});

const std_SessionNotAllowedError = t.struct("std.SessionNotAllowedError", {});

const std_InvalidVestingScheduleError = t.struct("std.InvalidVestingScheduleError", {});

const std_VestingLockedCoinsError = t.struct("std.VestingLockedCoinsError", {});

const sdk_Result = t.struct("sdk.Result", {
  responseBase: t.field(abci_ResponseBase, { json: "ResponseBase" }),
  gasWanted: t.field(t.int64, { json: "GasWanted" }),
  gasUsed: t.field(t.int64, { json: "GasUsed" }),
});

const params_Param = reprs.Param;

const auth_Params = t.struct("auth.Params", {
  maxMemoBytes: t.field(t.int64, { json: "max_memo_bytes" }),
  txSigLimit: t.field(t.int64, { json: "tx_sig_limit" }),
  txSizeCostPerByte: t.field(t.int64, { json: "tx_size_cost_per_byte" }),
  sigVerifyCostED25519: t.field(t.int64, { json: "sig_verify_cost_ed25519" }),
  sigVerifyCostSecp256k1: t.field(t.int64, { json: "sig_verify_cost_secp256k1" }),
  gasPricesChangeCompressor: t.field(t.int64, { json: "gas_price_change_compressor" }),
  targetGasRatio: t.field(t.int64, { json: "target_gas_ratio" }),
  initialGasPrice: t.field(std_GasPrice, { json: "initial_gasprice" }),
  unrestrictedAddrs: t.field(t.slice(reprs.Address), { json: "unrestricted_addrs" }),
  feeCollector: t.field(reprs.Address, { json: "fee_collector" }),
});

const auth_GenesisState = t.struct("auth.GenesisState", {
  params: auth_Params,
});

const auth_MsgCreateSession = t.struct("auth.MsgCreateSession", {
  creator: reprs.Address,
  sessionKey: t.field(crypto_PubKey, { json: "session_key" }),
  expiresAt: t.field(t.int64, { json: "expires_at" }),
  allowPaths: t.field(t.slice(t.string), { json: "allow_paths", omitEmpty: true }),
  spendLimit: t.field(reprs.Coins, { json: "spend_limit", omitEmpty: true }),
  spendPeriod: t.field(t.int64, { json: "spend_period", omitEmpty: true }),
});

const auth_MsgRevokeSession = t.struct("auth.MsgRevokeSession", {
  creator: reprs.Address,
  sessionKey: t.field(crypto_PubKey, { json: "session_key" }),
});

const auth_MsgRevokeAllSessions = t.struct("auth.MsgRevokeAllSessions", {
  creator: reprs.Address,
});

const bank_NoInputsError = t.struct("bank.NoInputsError", {});

const bank_NoOutputsError = t.struct("bank.NoOutputsError", {});

const bank_InputOutputMismatchError = t.struct("bank.InputOutputMismatchError", {});

const bank_MsgSend = t.struct("bank.MsgSend", {
  fromAddress: t.field(reprs.Address, { json: "from_address" }),
  toAddress: t.field(reprs.Address, { json: "to_address" }),
  amount: reprs.Coins,
});

const bank_Params = t.struct("bank.Params", {
  restrictedDenoms: t.field(t.slice(t.string), { json: "restricted_denoms" }),
});

const bank_GenesisState = t.struct("bank.GenesisState", {
  params: bank_Params,
});

const bank_TransferEvent = t.struct("bank.TransferEvent", {
  from: t.string,
  to: t.string,
  coins: reprs.Coins,
});

const chain_EventAttribute = t.struct("chain.EventAttribute", {
  key: t.string,
  value: t.string,
});

const chain_Event = t.struct("chain.Event", {
  type: t.string,
  attributes: t.field(t.slice(chain_EventAttribute), { json: "attrs" }),
  pkgPath: t.field(t.string, { json: "pkg_path" }),
});

const chain_StorageDepositEvent = t.struct("chain.StorageDepositEvent", {
  bytesDelta: t.field(t.int64, { json: "bytes_delta" }),
  feeDelta: t.field(std_Coin, { json: "fee_delta" }),
  pkgPath: t.field(t.string, { json: "pkg_path" }),
});

const chain_StorageUnlockEvent = t.struct("chain.StorageUnlockEvent", {
  bytesDelta: t.field(t.int64, { json: "bytes_delta" }),
  feeRefund: t.field(std_Coin, { json: "fee_refund" }),
  pkgPath: t.field(t.string, { json: "pkg_path" }),
  refundWithheld: t.field(t.bool, { json: "refund_withheld" }),
});

const vm_MsgCall = t.struct("vm.MsgCall", {
  caller: reprs.Address,
  send: reprs.Coins,
  maxDeposit: t.field(reprs.Coins, { json: "max_deposit" }),
  pkgPath: t.field(t.string, { json: "pkg_path" }),
  func: t.string,
  args: t.field(t.slice(t.string), { omitEmpty: true }),
});

const vm_MsgRun = t.struct("vm.MsgRun", {
  caller: reprs.Address,
  send: reprs.Coins,
  maxDeposit: t.field(reprs.Coins, { json: "max_deposit" }),
  package: t.pointer(std_MemPackage),
});

const vm_MsgAddPackage = t.struct("vm.MsgAddPackage", {
  creator: reprs.Address,
  package: t.pointer(std_MemPackage),
  send: reprs.Coins,
  maxDeposit: t.field(reprs.Coins, { json: "max_deposit" }),
});

const vm_MsgEnablePackage = t.struct("vm.MsgEnablePackage", {
  approver: reprs.Address,
  pkgPath: t.field(t.string, { json: "pkg_path" }),
  pkgHash: t.field(t.string, { json: "pkg_hash" }),
  pkgHeight: t.field(t.int64, { json: "pkg_height" }),
});

const vm_MsgRejectPackage = t.struct("vm.MsgRejectPackage", {
  sender: reprs.Address,
  pkgPath: t.field(t.string, { json: "pkg_path" }),
});

const vm_InvalidPkgPathError = t.struct("vm.InvalidPkgPathError", {});

const vm_NoRenderDeclError = t.struct("vm.NoRenderDeclError", {});

const vm_PkgExistError = t.struct("vm.PkgExistError", {});

const vm_InvalidStmtError = t.struct("vm.InvalidStmtError", {});

const vm_InvalidExprError = t.struct("vm.InvalidExprError", {});

const vm_TypeCheckError = t.struct("vm.TypeCheckError", {});

const vm_UnauthorizedUserError = t.struct("vm.UnauthorizedUserError", {});

const vm_InvalidPackageError = t.struct("vm.InvalidPackageError", {});

const vm_InvalidFileError = t.struct("vm.InvalidFileError", {});

const vm_ObjectNotFoundError = t.struct("vm.ObjectNotFoundError", {});

const vm_ExportSizeExceededError = t.struct("vm.ExportSizeExceededError", {});

const vm_ExportDepthExceededError = t.struct("vm.ExportDepthExceededError", {});

const vm_UnobservedSendError = t.struct("vm.UnobservedSendError", {});

const vm_UnspendableSendError = t.struct("vm.UnspendableSendError", {});

const vm_Params = t.struct("vm.Params", {
  sysNamesPkgPath: t.field(t.string, { json: "sysnames_pkgpath" }),
  sysCLAPkgPath: t.field(t.string, { json: "syscla_pkgpath" }),
  chainDomain: t.field(t.string, { json: "chain_domain" }),
  defaultDeposit: t.field(t.string, { json: "default_deposit" }),
  storagePrice: t.field(t.string, { json: "storage_price" }),
  storageFeeCollector: t.field(reprs.Address, { json: "storage_fee_collector" }),
  minGetReadDepth100: t.field(t.int64, { json: "min_get_read_depth_100" }),
  minSetReadDepth100: t.field(t.int64, { json: "min_set_read_depth_100" }),
  minWriteDepth100: t.field(t.int64, { json: "min_write_depth_100" }),
  fixedGetReadDepth100: t.field(t.int64, { json: "fixed_get_read_depth_100" }),
  fixedSetReadDepth100: t.field(t.int64, { json: "fixed_set_read_depth_100" }),
  fixedWriteDepth100: t.field(t.int64, { json: "fixed_write_depth_100" }),
  iterNextCostFlat: t.field(t.int64, { json: "iter_next_cost_flat" }),
  preprocessGasPerByte: t.field(t.int64, { json: "preprocess_gas_per_byte" }),
  codeSubmissionPolicy: t.field(t.string, { json: "code_submission_policy" }),
  codeSubmitters: t.field(t.slice(reprs.Address), { json: "code_submitters" }),
  pkgApprovers: t.field(t.slice(reprs.Address), { json: "pkg_approvers" }),
  runSubmitters: t.field(t.slice(reprs.Address), { json: "run_submitters" }),
  inertSubmissionCharge: t.field(t.string, { json: "inert_submission_charge" }),
  inertChargeCollector: t.field(reprs.Address, { json: "inert_charge_collector" }),
});

const vm_GenesisState = t.struct("vm.GenesisState", {
  params: vm_Params,
  realmParams: t.field(t.slice(params_Param), { json: "realm_params" }),
});

const gnoland_GnoAccount = t.struct("gnoland.GnoAccount", {
  baseAccount: t.field(std_BaseAccount, { json: "BaseAccount" }),
  attributes: t.uint64,
});

const gnoland_GnoSessionAccount = t.struct("gnoland.GnoSessionAccount", {
  baseSessionAccount: t.field(std_BaseSessionAccount, { json: "BaseSessionAccount" }),
  allowPaths: t.field(t.slice(t.string), { json: "allow_paths", omitEmpty: true }),
});

const gnoland_SignerAccountInfo = t.struct("gnoland.SignerAccountInfo", {
  address: reprs.Address,
  accountNum: t.field(t.uint64, { json: "account_num" }),
  sequence: t.uint64,
});

const gnoland_GnoTxMetadata = t.struct("gnoland.GnoTxMetadata", {
  timestamp: t.int64,
  blockHeight: t.field(t.int64, { json: "block_height", omitEmpty: true }),
  chainID: t.field(t.string, { json: "chain_id", omitEmpty: true }),
  failed: t.field(t.bool, { omitEmpty: true }),
  signerInfo: t.field(t.slice(gnoland_SignerAccountInfo), { json: "signer_info", omitEmpty: true }),
  gasUsed: t.field(t.int64, { json: "gas_used", omitEmpty: true }),
  gasWanted: t.field(t.int64, { json: "gas_wanted", omitEmpty: true }),
  source: t.field(t.string, { omitEmpty: true }),
  note: t.field(t.string, { omitEmpty: true }),
  originalTx: t.field(t.pointer(std_Tx), { json: "original_tx", omitEmpty: true }),
});

const gnoland_TxWithMetadata = t.struct("gnoland.TxWithMetadata", {
  tx: std_Tx,
  metadata: t.field(t.pointer(gnoland_GnoTxMetadata), { omitEmpty: true }),
});

const gnoland_GnoGenesisState = t.struct("gnoland.GnoGenesisState", {
  balances: t.slice(reprs.Balance),
  txs: t.slice(gnoland_TxWithMetadata),
  auth: auth_GenesisState,
  bank: bank_GenesisState,
  vm: vm_GenesisState,
  pastChainIDs: t.field(t.slice(t.string), { json: "past_chain_ids", omitEmpty: true }),
  initialHeight: t.field(t.int64, { json: "initial_height", omitEmpty: true }),
  gasReplayMode: t.field(t.string, { json: "gas_replay_mode", omitEmpty: true }),
});

export const bitarray = {
  BitArray: bitarray_BitArray,
};

export const merkle = {
  Proof: merkle_Proof,
  ProofOp: merkle_ProofOp,
  SimpleProof: merkle_SimpleProof,
  SimpleProofNode: merkle_SimpleProofNode,
};

export const secp256k1 = {
  PubKeySecp256k1: secp256k1_PubKeySecp256k1,
};

export const ed25519 = {
  PubKeyEd25519: ed25519_PubKeyEd25519,
};

export const multisig = {
  PubKeyMultisigThreshold: multisig_PubKeyMultisigThreshold,
};

export const abci = {
  BlockParams: abci_BlockParams,
  ConsensusParams: abci_ConsensusParams,
  Error: abci_Error,
  Event: abci_Event,
  EventString: abci_EventString,
  Header: abci_Header,
  LastCommitInfo: abci_LastCommitInfo,
  RequestBase: abci_RequestBase,
  RequestBeginBlock: abci_RequestBeginBlock,
  RequestCheckTx: abci_RequestCheckTx,
  RequestCommit: abci_RequestCommit,
  RequestDeliverTx: abci_RequestDeliverTx,
  RequestEcho: abci_RequestEcho,
  RequestEndBlock: abci_RequestEndBlock,
  RequestFlush: abci_RequestFlush,
  RequestInfo: abci_RequestInfo,
  RequestInitChain: abci_RequestInitChain,
  RequestQuery: abci_RequestQuery,
  RequestSetOption: abci_RequestSetOption,
  ResponseBase: abci_ResponseBase,
  ResponseBeginBlock: abci_ResponseBeginBlock,
  ResponseCheckTx: abci_ResponseCheckTx,
  ResponseCommit: abci_ResponseCommit,
  ResponseDeliverTx: abci_ResponseDeliverTx,
  ResponseEcho: abci_ResponseEcho,
  ResponseEndBlock: abci_ResponseEndBlock,
  ResponseException: abci_ResponseException,
  ResponseFlush: abci_ResponseFlush,
  ResponseInfo: abci_ResponseInfo,
  ResponseInitChain: abci_ResponseInitChain,
  ResponseQuery: abci_ResponseQuery,
  ResponseSetOption: abci_ResponseSetOption,
  StringError: abci_StringError,
  ValidatorParams: abci_ValidatorParams,
  ValidatorUpdate: abci_ValidatorUpdate,
  VoteInfo: abci_VoteInfo,
};

export const bft = {
  Block: bft_Block,
  BlockID: bft_BlockID,
  CanonicalBlockID: bft_CanonicalBlockID,
  CanonicalPartSetHeader: bft_CanonicalPartSetHeader,
  CanonicalProposal: bft_CanonicalProposal,
  CanonicalVote: bft_CanonicalVote,
  Commit: bft_Commit,
  CommitSig: bft_CommitSig,
  Data: bft_Data,
  DuplicateVoteEvidence: bft_DuplicateVoteEvidence,
  EventNewBlock: bft_EventNewBlock,
  EventNewBlockHeader: bft_EventNewBlockHeader,
  EventString: bft_EventString,
  EventTx: bft_EventTx,
  EventValidatorSetUpdates: bft_EventValidatorSetUpdates,
  EventVote: bft_EventVote,
  Header: bft_Header,
  Part: bft_Part,
  PartSetHeader: bft_PartSetHeader,
  Proposal: bft_Proposal,
  TxResult: bft_TxResult,
  Validator: bft_Validator,
  ValidatorSet: bft_ValidatorSet,
  Vote: bft_Vote,
};

export const std = {
  BaseAccount: std_BaseAccount,
  BaseSessionAccount: std_BaseSessionAccount,
  Coin: std_Coin,
  Fee: std_Fee,
  GasOverflowError: std_GasOverflowError,
  GasPrice: std_GasPrice,
  InsufficientCoinsError: std_InsufficientCoinsError,
  InsufficientFeeError: std_InsufficientFeeError,
  InsufficientFundsError: std_InsufficientFundsError,
  InternalError: std_InternalError,
  InvalidAddressError: std_InvalidAddressError,
  InvalidCoinsError: std_InvalidCoinsError,
  InvalidGasWantedError: std_InvalidGasWantedError,
  InvalidPubKeyError: std_InvalidPubKeyError,
  InvalidSequenceError: std_InvalidSequenceError,
  InvalidVestingScheduleError: std_InvalidVestingScheduleError,
  MemFile: std_MemFile,
  MemPackage: std_MemPackage,
  MemoTooLargeError: std_MemoTooLargeError,
  Msg: std_Msg,
  NoSignaturesError: std_NoSignaturesError,
  OutOfGasError: std_OutOfGasError,
  RestrictedTransferError: std_RestrictedTransferError,
  SessionExpiredError: std_SessionExpiredError,
  SessionLimitError: std_SessionLimitError,
  SessionNotAllowedError: std_SessionNotAllowedError,
  SessionNotFoundError: std_SessionNotFoundError,
  Signature: std_Signature,
  TooManySignaturesError: std_TooManySignaturesError,
  Tx: std_Tx,
  TxDecodeError: std_TxDecodeError,
  UnauthorizedError: std_UnauthorizedError,
  UnknownAddressError: std_UnknownAddressError,
  UnknownRequestError: std_UnknownRequestError,
  VestingLockedCoinsError: std_VestingLockedCoinsError,
  VestingSchedule: std_VestingSchedule,
};

export const sdk = {
  Result: sdk_Result,
};

export const params = {
  Param: params_Param,
};

export const auth = {
  GenesisState: auth_GenesisState,
  MsgCreateSession: auth_MsgCreateSession,
  MsgRevokeAllSessions: auth_MsgRevokeAllSessions,
  MsgRevokeSession: auth_MsgRevokeSession,
  Params: auth_Params,
};

export const bank = {
  GenesisState: bank_GenesisState,
  InputOutputMismatchError: bank_InputOutputMismatchError,
  MsgSend: bank_MsgSend,
  NoInputsError: bank_NoInputsError,
  NoOutputsError: bank_NoOutputsError,
  Params: bank_Params,
  TransferEvent: bank_TransferEvent,
};

export const chain = {
  Event: chain_Event,
  EventAttribute: chain_EventAttribute,
  StorageDepositEvent: chain_StorageDepositEvent,
  StorageUnlockEvent: chain_StorageUnlockEvent,
};

export const vm = {
  ExportDepthExceededError: vm_ExportDepthExceededError,
  ExportSizeExceededError: vm_ExportSizeExceededError,
  GenesisState: vm_GenesisState,
  InvalidExprError: vm_InvalidExprError,
  InvalidFileError: vm_InvalidFileError,
  InvalidPackageError: vm_InvalidPackageError,
  InvalidPkgPathError: vm_InvalidPkgPathError,
  InvalidStmtError: vm_InvalidStmtError,
  MsgAddPackage: vm_MsgAddPackage,
  MsgCall: vm_MsgCall,
  MsgEnablePackage: vm_MsgEnablePackage,
  MsgRejectPackage: vm_MsgRejectPackage,
  MsgRun: vm_MsgRun,
  NoRenderDeclError: vm_NoRenderDeclError,
  ObjectNotFoundError: vm_ObjectNotFoundError,
  Params: vm_Params,
  PkgExistError: vm_PkgExistError,
  TypeCheckError: vm_TypeCheckError,
  UnauthorizedUserError: vm_UnauthorizedUserError,
  UnobservedSendError: vm_UnobservedSendError,
  UnspendableSendError: vm_UnspendableSendError,
};

export const gnoland = {
  GnoAccount: gnoland_GnoAccount,
  GnoGenesisState: gnoland_GnoGenesisState,
  GnoSessionAccount: gnoland_GnoSessionAccount,
  GnoTxMetadata: gnoland_GnoTxMetadata,
  SignerAccountInfo: gnoland_SignerAccountInfo,
  TxWithMetadata: gnoland_TxWithMetadata,
};

export const crypto = {
  PubKey: crypto_PubKey,
};

/** Registers every tm2 and gno.land concrete type under its Go type URL. */
export function registerGnoTypes(cdc: Codec): Codec {
  return cdc
    .declareInterface(crypto_PubKey)
    .declareInterface(abci_Header)
    .declareInterface(abci_Error)
    .declareInterface(abci_Event)
    .declareInterface(std_Msg)
    .register("/tm.BitArray", bitarray_BitArray)
    .register("/tm.ProofOp", merkle_ProofOp)
    .register("/tm.Proof", merkle_Proof)
    .register("/tm.SimpleProof", merkle_SimpleProof)
    .register("/tm.SimpleProofNode", merkle_SimpleProofNode)
    .register("/tm.PubKeySecp256k1", secp256k1_PubKeySecp256k1, [crypto_PubKey])
    .register("/tm.PubKeyEd25519", ed25519_PubKeyEd25519, [crypto_PubKey])
    .register("/tm.PubKeyMultisig", multisig_PubKeyMultisigThreshold, [crypto_PubKey])
    .register("/abci.RequestBase", abci_RequestBase)
    .register("/abci.RequestEcho", abci_RequestEcho)
    .register("/abci.RequestFlush", abci_RequestFlush)
    .register("/abci.RequestInfo", abci_RequestInfo)
    .register("/abci.RequestSetOption", abci_RequestSetOption)
    .register("/abci.RequestInitChain", abci_RequestInitChain)
    .register("/abci.RequestQuery", abci_RequestQuery)
    .register("/abci.RequestBeginBlock", abci_RequestBeginBlock)
    .register("/abci.RequestCheckTx", abci_RequestCheckTx)
    .register("/abci.RequestDeliverTx", abci_RequestDeliverTx)
    .register("/abci.RequestEndBlock", abci_RequestEndBlock)
    .register("/abci.RequestCommit", abci_RequestCommit)
    .register("/abci.ResponseBase", abci_ResponseBase)
    .register("/abci.ResponseException", abci_ResponseException)
    .register("/abci.ResponseEcho", abci_ResponseEcho)
    .register("/abci.ResponseFlush", abci_ResponseFlush)
    .register("/abci.ResponseInfo", abci_ResponseInfo)
    .register("/abci.ResponseSetOption", abci_ResponseSetOption)
    .register("/abci.ResponseInitChain", abci_ResponseInitChain)
    .register("/abci.ResponseQuery", abci_ResponseQuery)
    .register("/abci.ResponseBeginBlock", abci_ResponseBeginBlock)
    .register("/abci.ResponseCheckTx", abci_ResponseCheckTx)
    .register("/abci.ResponseDeliverTx", abci_ResponseDeliverTx)
    .register("/abci.ResponseEndBlock", abci_ResponseEndBlock)
    .register("/abci.ResponseCommit", abci_ResponseCommit)
    .register("/abci.StringError", abci_StringError, [abci_Error])
    .register("/abci.ConsensusParams", abci_ConsensusParams)
    .register("/abci.BlockParams", abci_BlockParams)
    .register("/abci.ValidatorParams", abci_ValidatorParams)
    .register("/abci.ValidatorUpdate", abci_ValidatorUpdate)
    .register("/abci.LastCommitInfo", abci_LastCommitInfo)
    .register("/abci.VoteInfo", abci_VoteInfo)
    .register("/abci.EventString", abci_EventString, [abci_Event])
    .register("/tm.Proposal", bft_Proposal)
    .register("/tm.Block", bft_Block)
    .register("/tm.Header", bft_Header)
    .register("/tm.Data", bft_Data)
    .register("/tm.Commit", bft_Commit)
    .register("/tm.BlockID", bft_BlockID)
    .register("/tm.CommitSig", bft_CommitSig)
    .register("/tm.Vote", bft_Vote)
    .register("/tm.Part", bft_Part)
    .register("/tm.PartSetHeader", bft_PartSetHeader)
    .register("/tm.CanonicalBlockID", bft_CanonicalBlockID)
    .register("/tm.CanonicalPartSetHeader", bft_CanonicalPartSetHeader)
    .register("/tm.CanonicalProposal", bft_CanonicalProposal)
    .register("/tm.CanonicalVote", bft_CanonicalVote)
    .register("/tm.Validator", bft_Validator)
    .register("/tm.ValidatorSet", bft_ValidatorSet)
    .register("/tm.EventNewBlock", bft_EventNewBlock)
    .register("/tm.EventNewBlockHeader", bft_EventNewBlockHeader)
    .register("/tm.EventTx", bft_EventTx)
    .register("/tm.EventVote", bft_EventVote)
    .register("/tm.EventString", bft_EventString)
    .register("/tm.EventValidatorSetUpdates", bft_EventValidatorSetUpdates)
    .register("/tm.DuplicateVoteEvidence", bft_DuplicateVoteEvidence)
    .register("/tm.TxResult", bft_TxResult)
    .register("/std.BaseAccount", std_BaseAccount)
    .register("/std.BaseSessionAccount", std_BaseSessionAccount)
    .register("/std.VestingSchedule", std_VestingSchedule)
    .register("/std.Coin", std_Coin)
    .register("/std.GasPrice", std_GasPrice)
    .register("/std.Tx", std_Tx)
    .register("/std.Fee", std_Fee)
    .register("/std.Signature", std_Signature)
    .register("/std.MemFile", std_MemFile)
    .register("/std.MemPackage", std_MemPackage)
    .register("/std.InternalError", std_InternalError, [abci_Error])
    .register("/std.TxDecodeError", std_TxDecodeError, [abci_Error])
    .register("/std.InvalidSequenceError", std_InvalidSequenceError, [abci_Error])
    .register("/std.UnauthorizedError", std_UnauthorizedError, [abci_Error])
    .register("/std.InsufficientFundsError", std_InsufficientFundsError, [abci_Error])
    .register("/std.UnknownRequestError", std_UnknownRequestError, [abci_Error])
    .register("/std.InvalidAddressError", std_InvalidAddressError, [abci_Error])
    .register("/std.UnknownAddressError", std_UnknownAddressError, [abci_Error])
    .register("/std.InvalidPubKeyError", std_InvalidPubKeyError, [abci_Error])
    .register("/std.InsufficientCoinsError", std_InsufficientCoinsError, [abci_Error])
    .register("/std.InvalidCoinsError", std_InvalidCoinsError, [abci_Error])
    .register("/std.InvalidGasWantedError", std_InvalidGasWantedError, [abci_Error])
    .register("/std.OutOfGasError", std_OutOfGasError, [abci_Error])
    .register("/std.MemoTooLargeError", std_MemoTooLargeError, [abci_Error])
    .register("/std.InsufficientFeeError", std_InsufficientFeeError, [abci_Error])
    .register("/std.TooManySignaturesError", std_TooManySignaturesError, [abci_Error])
    .register("/std.NoSignaturesError", std_NoSignaturesError, [abci_Error])
    .register("/std.GasOverflowError", std_GasOverflowError, [abci_Error])
    .register("/std.RestrictedTransferError", std_RestrictedTransferError, [abci_Error])
    .register("/std.SessionExpiredError", std_SessionExpiredError, [abci_Error])
    .register("/std.SessionNotFoundError", std_SessionNotFoundError, [abci_Error])
    .register("/std.SessionLimitError", std_SessionLimitError, [abci_Error])
    .register("/std.SessionNotAllowedError", std_SessionNotAllowedError, [abci_Error])
    .register("/std.InvalidVestingScheduleError", std_InvalidVestingScheduleError, [abci_Error])
    .register("/std.VestingLockedCoinsError", std_VestingLockedCoinsError, [abci_Error])
    .register("/tm.Result", sdk_Result)
    .register("/params.Param", params_Param)
    .register("/auth.GenesisState", auth_GenesisState)
    .register("/auth.Params", auth_Params)
    .register("/auth.m_create_session", auth_MsgCreateSession, [std_Msg])
    .register("/auth.m_revoke_session", auth_MsgRevokeSession, [std_Msg])
    .register("/auth.m_revoke_all_sessions", auth_MsgRevokeAllSessions, [std_Msg])
    .register("/bank.NoInputsError", bank_NoInputsError, [abci_Error])
    .register("/bank.NoOutputsError", bank_NoOutputsError, [abci_Error])
    .register("/bank.InputOutputMismatchError", bank_InputOutputMismatchError, [abci_Error])
    .register("/bank.MsgSend", bank_MsgSend, [std_Msg])
    .register("/bank.GenesisState", bank_GenesisState)
    .register("/bank.Params", bank_Params)
    .register("/bank.TransferEvent", bank_TransferEvent, [abci_Event])
    .register("/tm.EventAttribute", chain_EventAttribute)
    .register("/tm.Event", chain_Event, [abci_Event])
    .register("/tm.StorageDepositEvent", chain_StorageDepositEvent, [abci_Event])
    .register("/tm.StorageUnlockEvent", chain_StorageUnlockEvent, [abci_Event])
    .register("/vm.m_call", vm_MsgCall, [std_Msg])
    .register("/vm.m_run", vm_MsgRun, [std_Msg])
    .register("/vm.m_addpkg", vm_MsgAddPackage, [std_Msg])
    .register("/vm.m_enable_pkg", vm_MsgEnablePackage, [std_Msg])
    .register("/vm.m_reject_pkg", vm_MsgRejectPackage, [std_Msg])
    .register("/vm.InvalidPkgPathError", vm_InvalidPkgPathError, [abci_Error])
    .register("/vm.NoRenderDeclError", vm_NoRenderDeclError, [abci_Error])
    .register("/vm.PkgExistError", vm_PkgExistError, [abci_Error])
    .register("/vm.InvalidStmtError", vm_InvalidStmtError, [abci_Error])
    .register("/vm.InvalidExprError", vm_InvalidExprError, [abci_Error])
    .register("/vm.TypeCheckError", vm_TypeCheckError, [abci_Error])
    .register("/vm.UnauthorizedUserError", vm_UnauthorizedUserError, [abci_Error])
    .register("/vm.InvalidPackageError", vm_InvalidPackageError, [abci_Error])
    .register("/vm.InvalidFileError", vm_InvalidFileError, [abci_Error])
    .register("/vm.ObjectNotFoundError", vm_ObjectNotFoundError, [abci_Error])
    .register("/vm.ExportSizeExceededError", vm_ExportSizeExceededError, [abci_Error])
    .register("/vm.ExportDepthExceededError", vm_ExportDepthExceededError, [abci_Error])
    .register("/vm.UnobservedSendError", vm_UnobservedSendError, [abci_Error])
    .register("/vm.UnspendableSendError", vm_UnspendableSendError, [abci_Error])
    .register("/vm.GenesisState", vm_GenesisState)
    .register("/vm.Params", vm_Params)
    .register("/gno.Account", gnoland_GnoAccount)
    .register("/gno.SessionAccount", gnoland_GnoSessionAccount)
    .register("/gno.GenesisState", gnoland_GnoGenesisState)
    .register("/gno.TxWithMetadata", gnoland_TxWithMetadata)
    .register("/gno.GnoTxMetadata", gnoland_GnoTxMetadata)
    .register("/gno.SignerAccountInfo", gnoland_SignerAccountInfo);
}
